name: Publish to NPM

on:
  workflow_dispatch:
    inputs:
      areYouSure:
        description: "Are you sure? Type YES to proceed"
        required: true
        default: "NO!"

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.areYouSure == 'YES' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install
      - run: npm whoami
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
