name: Publish to NPM

on:
  workflow_dispatch:
    inputs:
      areYouSure:
        description: "Are you sure? Type YES to proceed"
        required: true
        default: "NO!"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ github.event.inputs.areYouSure == 'YES' }}
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
